# Generated by Django 4.1.5 on 2023-02-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_alter_basicinfo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='robot_id',
            field=models.CharField(max_length=50),
        ),
    ]
