# Generated by Django 4.1.5 on 2023-02-01 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_alter_basicinfo_options'),
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='robot_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='robot.basicinfo'),
        ),
        migrations.AddField(
            model_name='operator',
            name='status',
            field=models.BooleanField(choices=[('True', 'True'), ('False', 'False')], default='False'),
        ),
    ]
