# Generated by Django 4.1.5 on 2023-02-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_operator_robot_id_operator_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='status',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], default='False', max_length=50, null=True),
        ),
    ]
