# Generated by Django 4.1.5 on 2023-01-24 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_transactionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rider.rider'),
        ),
    ]
