# Generated by Django 4.1.7 on 2023-03-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0005_rider_is_pending_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='pending_payment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
