# Generated by Django 4.1.5 on 2023-02-03 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('robot', '0003_alter_basicinfo_options'),
        ('rider', '0003_transactionhistory_rider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_km', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Cost Per Kilometer',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.IntegerField(blank=True, null=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('pickup_lat', models.DecimalField(decimal_places=8, default=None, max_digits=10, verbose_name='Latitude')),
                ('pickup_lng', models.DecimalField(decimal_places=8, default=None, max_digits=11, verbose_name='Longitude')),
                ('pickup_datetime', models.DateTimeField()),
                ('dropoff_location', models.CharField(blank=True, max_length=255, null=True)),
                ('dropoff_datetime', models.DateTimeField(blank=True, null=True)),
                ('distance_traveled', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=255)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rider.rider')),
                ('robot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='robot.basicinfo')),
            ],
        ),
    ]
