# Generated by Django 4.1.5 on 2023-02-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0004_alter_trip_pickup_lat_alter_trip_pickup_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='estimating_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
