# Generated by Django 4.1.5 on 2023-02-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0005_trip_estimating_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='estimating_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
