# Generated by Django 4.1.7 on 2023-02-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0007_alter_trip_rider_alter_trip_robot_alter_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_feedback',
            field=models.CharField(choices=[('happy', 'happy'), ('angry', 'angry'), ('liked', 'liked'), ('disliked', 'disliked')], default='liked', max_length=200),
        ),
    ]
