# Generated by Django 4.1.7 on 2023-02-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0008_trip_comment_trip_trip_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='estimating_distance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
