# Generated by Django 4.1.7 on 2023-02-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0009_trip_estimating_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('initiated', 'initiated'), ('accepted', 'accepted'), ('started', 'started'), ('completed', 'completed'), ('canceled', 'canceled')], default='initiated', max_length=255),
        ),
    ]
