# Generated by Django 4.1.7 on 2023-03-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0010_alter_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='ride_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
