# Generated by Django 4.1.7 on 2023-03-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0011_trip_ride_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fare',
            options={'verbose_name_plural': 'Cost Per Miles'},
        ),
        migrations.RenameField(
            model_name='fare',
            old_name='cost_per_km',
            new_name='cost_per_mi',
        ),
    ]
